//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinterIntegrationTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\models\\VdV_Reactor\\VdV_Reactor_Dynamic_Config.json")]
        public string DynamicVdVACMConfig
        {
            get
            {
                return ((string)(this["DynamicVdVACMConfig"]));
            }
            set
            {
                this["DynamicVdVACMConfig"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VdV_Reactor_Dynamic_Config.json")]
        public string DynamicVdVACMFilename
        {
            get
            {
                return ((string)(this["DynamicVdVACMFilename"]));
            }
            set
            {
                this["DynamicVdVACMFilename"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\models\\VdV_Reactor")]
        public string DynamicVdVACMDir
        {
            get
            {
                return ((string)(this["DynamicVdVACMDir"]));
            }
            set
            {
                this["DynamicVdVACMDir"] = value;
            }
        }
    }
}
